### ISSUE TITLE
blast2bed issue

### ISSUE THREAD

**Issue by jcerca** [jlevy44/PolyCRACKER-Unofficial-Mirror#6]
Hi Joshua,

thank you so much for making this unofficial mirror and for this software. I have a Tetraploid genome and I need to break it on two subgenomes. This software is just what I needed. I managed to install the software in the docker, but after failing due to memory constraints (3.2 gb genome), I did a conda install as you outlined.

After installing with conda, I did the following commands:

`polycracker splitFasta -d ./ -i scalesia_atractyloides.chrOnly.fasta`
`polycracker writeKmerCount -d ./ -m 500 -k 15`
`polycracker kmer2Fasta -k ./kmercount_files/`
`polycracker blast_kmers -m 250 --reference_genome ./scalesia_atractyloides.chrOnly.fasta --kmer_fasta kmercount_files/scalesia_atractyloides.chrOnly_split.kcount.fa -o ./blast.sam -t 20`
`polycracker blast2bed -i ./blast.sam -o ./blasted.bed`

This last command gives me the following problem:

```
Traceback (most recent call last):
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/bin/polycracker", line 8, in <module>
    sys.exit(polycracker())
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/polycracker/polycracker.py", line 272, in blast2bed
    f2.write('\t'.join([l1] + ['0', str(int(l1.split('_')[-1]) - int(l1.split('_')[-2]))] + [line.split('\t')[0]]) + '\n')
ValueError: invalid literal for int() with base 10: 'ScDrF4C'
```

I repeated the commands with the test dataset and I found the same problem. When I copied the sam file from my HPC to the docker and ran the blast2bed function I had the same problem - this leads me to exclude an installation problem - maybe I did something wrong? Do you mind sharing the full pipeline and code? I tried digging it from the nextflow file but I did not manage it.

Thank you.

**Comment by jlevy44** [comment]
Hi @jcerca , this is an interesting issue. Can you print the first line of the sam output file? Could maybe be an updated version of bbmap that is generating the output for naming conventions on the fasta name (was the file chunked first?). You need to make sure that the fasta has been broken into smaller chunks. Looks like you did this, but can you print the head of the FAI file (fasta index) of the chunked fasta? The blast command should reference the chunked fasta, not the entire fasta:

**_split.fa**
```
polycracker blast_kmers -m 250 --reference_genome ./scalesia_atractyloides.chrOnly_split.fa ...
```

**Comment by jcerca** [comment]
That solved it.
