### ISSUE TITLE
blast2bed error -

### ISSUE THREAD

**Issue by jcerca** [jlevy44/PolyCRACKER-Unofficial-Mirror#7]
Hi,

I've been running polycracker but hit a error on blast2bed.
Here are the previous commands:

```
polycracker splitFasta -d ./ -i scalesia_atractyloides.chrOnly.fasta
polycracker writeKmerCount -d ./ -m 500 -l 15 -k kmercount_files
polycracker kmer2Fasta -k ./kmercount_files/
polycracker blast_kmers -m 250 --reference_genome ./scalesia_atractyloides.chrOnly_split.fa --kmer_fasta kmercount_files/scalesia_atractyloides.chrOnly_split.kcount.fa -o ./blast.sam -t 30
```

So far, so good. After this, I tried using blast2bed:
```
polycracker blast2bed -i ./blast.sam -o blasted.bed
```
But got the following error:

```
Traceback (most recent call last):
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/bin/polycracker", line 8, in <module>
    sys.exit(polycracker())
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/click/core.py", line 1259, in
invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/click/core.py", line 1066, in
invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/polycracker/polycracker.py", line 280, in blast2bed
    b = pybedtools.BedTool(output_bed_file).sort().merge(c=4,o='collapse')
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/pybedtools/bedtool.py", line 401, in wrapped
    decode_output=decode_output,
  File "/data/bigexpansion/jcerca/local_bin/conda/envs/pCRACKER_p27/lib/python2.7/site-packages/pybedtools/helpers.py", line 455, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

        bedtools merge -o collapse -i /tmp/pybedtools.phWo7x.tmp -c 4

Error message was:
Error: line number 448274032 of file /tmp/pybedtools.phWo7x.tmp has 7 fields, but 4 were expected.
```

**Comment by jcerca** [comment]
Hi,

I finally managed to get docker running and have come across the same issue.

I copy it below. Thank you for your time in advance.

```
grep "Error" .nextflowlog
  Error message was:
  Error: line number 322016112 of file /tmp/pybedtools.zc6gHt.tmp has 7 fields, but 4 were expected.
```

**Comment by jlevy44** [comment]
Can you post one of the lines?

Try with the --bb=1 option enabled for blast2bed. I'm pretty sure running blast itself has been deprecated in favor of bbtools.
```
polycracker blast2bed -i ./blast.sam -o blasted.bed --bb 1
```

**Comment by jcerca** [comment]
Hi Joshua,

Thank you for your answer and sorry for the delayed answer. I think the problem was that polycracker is writting tons of files in `/tmp`. Our cluster had a head node with only 70Gb. The second cluster I work with, and tried my dataset, also complained. It may be good to include a specified folder (like adding a `--tmpdir` function to polycracker), instead of writing files in /tmp The error is because the file was corrupted, due to lack of memory, I assume.

For future reference, and for others, I attach the stats from a docker run on a 3.2 Gb genome with >70% repeats.

![timeline](https://user-images.githubusercontent.com/20044964/104464446-387aa200-55b3-11eb-9d87-68a60091f025.png)
