### ISSUE TITLE
Blast2Bed

### ISSUE THREAD

**Issue by EmilyPhelps** [jlevy44/PolyCRACKER-Unofficial-Mirror#9]
Hi, I'm trying to use polycracker to identify subgenomes in a polyploid teleost. The genome is 3.6GB and dont know how many WGD it has undergone yet, so I am just testing for 2 currently.

I am getting an error when running the blast2be command. I have tried running the whole pipeline or just the individual Blast2Bed command. 

My command is:
```
polycracker blast2bed -i ./blast.sam -o blasted.bed -b 1 -l 1 2> error.log
```

My error log is:
```
root@4d41628e40cf:~/polycracker# cat error.log
Traceback (most recent call last):
  File "/opt/conda/bin/polycracker", line 11, in <module>
    sys.exit(polycracker())
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/polycracker/polycracker.py", line 280, in blast2bed
    b = pybedtools.BedTool(output_bed_file).sort().merge(c=4,o='collapse')
  File "/opt/conda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 840, in decorated
    result = method(self, *args, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 345, in wrapped
    decode_output=decode_output,
  File "/opt/conda/lib/python2.7/site-packages/pybedtools/helpers.py", line 434, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

        bedtools merge -o collapse -i /tmp/pybedtools.xO1KR_.tmp -c 4

Error message was:

*****
***** ERROR: Requested column 4, but database file /tmp/pybedtools.xO1KR_.tmp only has fields 1 - 0.
```
Cheers in advanced!

**Comment by jlevy44** [comment]
#7

**Comment by jlevy44** [comment]
Thanks @EmilyPhelps I will try to get to this soon, please message again if I do not get back soon. Thanks!

**Comment by EmilyPhelps** [comment]
Hi- I have resolved this issue now. Similar to issue N#7, it was relating to the size of the genome and RAM usage. Our genome was 3.6 GB. This was solved by setting the 'sample sensitivity' in the config file to 5 rather than one. The solution was mentioned in the published paper, but there was no mention of the parameter to modify- Thought it might be worth including in the readme. Great software though, very helpful thanks!

**Comment by kashiff007** [comment]
Hi, I am facing same issue:

```
[92/017141] process > splitFastaProcess (1)          [100%] 1 of 1 ✔
[a3/71108f] process > writeKmerCount                 [100%] 1 of 1 ✔
[da/71d026] process > kmer2Fasta (1)                 [100%] 1 of 1 ✔
[e9/aef2c3] process > createOrigDB (1)               [100%] 1 of 1 ✔
[fc/5cb268] process > BlastOff (1)                   [100%] 1 of 1 ✔
[66/1a9099] process > blast2bed (1)                  [100%] 1 of 1, failed: 1 ✘
[-        ] process > genClusterMatrix_kmerPreval... -
[-        ] process > transform                      -
[-        ] process > cluster                        -
[-        ] process > subgenomeExtraction            -
/ibex/scratch/projects/c2141/User_kashif_nawaz/LTR_RT_cluster_analysis_for_subgenome_separation/PolyCracker/polycracker/work/fc/5cb2
681f885283ac0b0ba396ba97b2

WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more 
info.
Error executing process > 'blast2bed (1)'
```

I also tried with increasing the sampling_sensitivity. My genome size is ~500 mb. Could you please provide with possible suggestions?

**Comment by jlevy44** [comment]
Hi @kashiff007 have you consulted #7 ? Can you output your directory structure and file sizes? You can also try running the individual python command and see if there are additional issues.

**Comment by kashiff007** [comment]
@jlevy44  I have checked #7 and as it explained it requires a command to assign a temp directly with command --tmpdir. 
<img width="820" alt="image" src="https://user-images.githubusercontent.com/16431099/170883013-7308aa37-82f5-4def-8b01-c94cbaddde96.png">

I am unable to find --tmpdir (or similar) option polycracker.

The error I am getting is:
```
Error bedtools merge -o collapse -i /tmp/pybedtools.lPG2lS.tmp -c 4
  
  Error message was:
  
  *****
  ***** ERROR: Requested column 4, but database file /tmp/pybedtools.lPG2lS.tmp only has fields 1 - 0.
```

As you suggested in #7 I also wanted to run the following command :
`polycracker blast2bed -i ./blast.sam -o blasted.bed --bb 1`

But I do not have blast.sam file in my output.

My output dir looks like:
```
-rwxr-xr-x 1 nawazk ibex-c2141  19K May 29 20:11 venn.py
-rwxr-xr-x 1 nawazk ibex-c2141  80K May 29 20:11 utilities.py
-rwxr-xr-x 1 nawazk ibex-c2141  149 May 29 20:11 runCluster.sh
-rwxr-xr-x 1 nawazk ibex-c2141  94K May 29 20:11 repeats.py
-rwxr-xr-x 1 nawazk ibex-c2141 157K May 29 20:11 polycracker.py
-rwxr-xr-x 1 nawazk ibex-c2141   76 May 29 20:11 __init__.py
-rwxr-xr-x 1 nawazk ibex-c2141 1.9K May 29 20:11 helper.py
-rwxr-xr-x 1 nawazk ibex-c2141 9.2K May 29 20:11 format.py
drwxr-sr-x 2 nawazk ibex-c2141    2 May 29 20:11 fasta_files
-rwxr-xr-x 1 nawazk ibex-c2141  14K May 29 20:11 polycracker.nf
-rwxr-xr-x 1 nawazk ibex-c2141 1.9K May 29 20:12 config_polyCRACKER.txt
drwxr-sr-x 3 nawazk ibex-c2141    1 May 29 20:12 test_data
drwxr-sr-x 5 nawazk ibex-c2141    3 May 29 20:13 test_results
drwxr-sr-x 2 nawazk ibex-c2141    0 May 29 20:13 analysisOutputs
-rw-r--r-- 1 nawazk ibex-c2141 649K May 29 20:13 correspondenceOriginal.bed
-rw-r--r-- 1 nawazk ibex-c2141 649K May 29 20:13 correspondence.bed
-rw-r--r-- 1 nawazk ibex-c2141  234 May 29 20:14 W6-48549-006.bp.p_ctg_split26.sh
drwxr-sr-x 2 nawazk ibex-c2141    2 May 29 20:15 kmercount_files
drwxr-sr-x 4 nawazk ibex-c2141    2 May 29 20:15 ref
drwxr-sr-x 8 nawazk ibex-c2141    6 May 29 20:20 work
drwxr-sr-x 2 nawazk ibex-c2141    1 May 29 20:20 blast_files
-rw-r--r-- 1 nawazk ibex-c2141    0 May 29 20:20 blasted.bed
-rw-r--r-- 1 nawazk ibex-c2141 6.9K May 29 20:20 timeline.html
-rw-r--r-- 1 nawazk ibex-c2141  150 May 29 20:20 submission_history.0.txt
-rw------- 1 nawazk ibex-c2141 3.0K May 29 20:20 flowchart.dot
-rw-r--r-- 1 nawazk ibex-c2141 360K May 29 20:20 scaffolds_stats.p
-rw-r--r-- 1 nawazk ibex-c2141  99K May 29 20:21 kmers_per_subsequence.png
```
Most of the files inside the directory has zero size.

**Comment by kashiff007** [comment]
While running the command individually:
1. `polycracker splitFasta -d ./ -i W6-48549-006.bp.p_ctg.fasta`
> produced two files:
> -rw-r--r-- 1 nawazk ibex-c2141 445298 May 29 20:52 correspondence.bed
> -rw-r--r-- 1 nawazk ibex-c2141 445298 May 29 20:52 correspondenceOriginal.bed

**Comment by jlevy44** [comment]
Can you return the output of:
```
ls blast_files
```
? 

It is possible that bbtools did not execute to completion (BlastOff memory error). You may want to make sure the memory allocated in the config file is less than the system specs.

**Comment by jlevy44** [comment]
Your config file may be misspecified.

**Comment by jlevy44** [comment]
Reopening this issue for additional discussion.

**Comment by kashiff007** [comment]
Thanks for bearing with me, I think figure out the step of blast2bed:
blast2bed was using --low_memory=0, and when I changed it to --low_memory=100 it worked fine.
It didn't showed any further error and executed all the process.
```
[bd/825913] process > splitFastaProcess (1)               [100%] 1 of 1 ✔
[54/5c6f43] process > writeKmerCount                      [100%] 1 of 1 ✔
[f5/c84f2b] process > kmer2Fasta (1)                      [100%] 1 of 1 ✔
[b8/cc992e] process > createOrigDB (1)                    [100%] 1 of 1 ✔
[10/35b2b5] process > BlastOff (1)                        [100%] 1 of 1 ✔
[68/5f3fc9] process > blast2bed (1)                       [100%] 1 of 1 ✔
[03/f9e01f] process > genClusterMatrix_kmerPrevalence (1) [100%] 1 of 1 ✔
[04/ee6536] process > transform (1)                       [100%] 1 of 1 ✔
[e4/bdd963] process > cluster (1)                         [100%] 1 of 1 ✔
[c7/191d93] process > subgenomeExtraction (1)             [100%] 1 of 1 ✔

```

I appreciate your help.
